### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [hydroshare/hydroshare_jupyter_sync#48]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.10. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary hydroshare-jupyter-sync -w /tmp/ext hydroshare-jupyter-sync==0.1.10
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting hydroshare-jupyter-sync==0.1.10
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ebb/82895e0c48f1f/hydroshare_jupyter_sync-0.1.10.tar.gz (518 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-d6e5ug70/hydroshare-jupyter-sync/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-d6e5ug70/hydroshare-jupyter-sync/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-d6e5ug70/hydroshare-jupyter-sync/pip-egg-info
         cwd: /tmp/pip-wheel-d6e5ug70/hydroshare-jupyter-sync/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-d6e5ug70/hydroshare-jupyter-sync/setup.py", line 27, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by aaraney** [comment]
Thanks for reporting this @thatch. I plan to move dependencies into `setup.cfg` in the future and likely remove `requirements.txt` all together. With that in mind, I will close this and #49 and ref the PR that changes how we pull in dependencies here.
